destroy

diff --git a/.github/workflows/waf-on-ce-aws-destroy.yml b/.github/workflows/waf-on-ce-aws-destroy.yml
--- a/.github/workflows/waf-on-ce-aws-destroy.yml
+++ b/.github/workflows/waf-on-ce-aws-destroy.yml
@@ -8,230 +8,230 @@ on:
   workflow_dispatch:
 
 jobs:
-  volt_mesh_site_destroy:
-    name: "F5 XC WAF"
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./xc
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # volt_mesh_site_destroy:
+  #   name: "F5 XC WAF"
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       working-directory: ./xc
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Setup Terraform Backend
-        id: backend
-        run: |
-          cat > backend.tf << EOF
-          terraform { 
-            cloud {
-              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
-              workspaces {
-                name = "${{ secrets.TF_CLOUD_WORKSPACE_XC }}"
-              }
-            }
-          }
-          EOF
-          echo "${{secrets.P12}}" | base64 -d > api.p12
+  #     - name: Setup Terraform Backend
+  #       id: backend
+  #       run: |
+  #         cat > backend.tf << EOF
+  #         terraform { 
+  #           cloud {
+  #             organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
+  #             workspaces {
+  #               name = "${{ secrets.TF_CLOUD_WORKSPACE_XC }}"
+  #             }
+  #           }
+  #         }
+  #         EOF
+  #         echo "${{secrets.P12}}" | base64 -d > api.p12
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+  #     - name: Terraform Init
+  #       id: init
+  #       run: terraform init
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
+  #     - name: Terraform Plan
+  #       id: plan
+  #       if: github.event_name == 'pull_request'
+  #       run: terraform plan -no-color -input=false
+  #       continue-on-error: true
 
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - uses: actions/github-script@v6
+  #       if: github.event_name == 'pull_request'
+  #       env:
+  #         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         script: |
+  #           const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+  #           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+  #           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+  #           <details><summary>Show Plan</summary>
+  #           \`\`\`\n
+  #           ${process.env.PLAN}
+  #           \`\`\`
+  #           </details>
+  #           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+  #           github.rest.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: output
+  #           })
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/destroy-waf-aws-ce' && github.event_name == 'push'
-        run: terraform destroy -auto-approve -input=false
+  #     - name: Terraform Apply
+  #       if: github.ref == 'refs/heads/destroy-waf-aws-ce' && github.event_name == 'push'
+  #       run: terraform destroy -auto-approve -input=false
 
-  terraform_boutique:
-    name: "Boutique app"
-    runs-on: ubuntu-latest
-    needs: [volt_mesh_site_destroy]
-    defaults:
-      run:
-        working-directory: ./shared/boutique
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # terraform_boutique:
+  #   name: "Boutique app"
+  #   runs-on: ubuntu-latest
+  #   needs: [volt_mesh_site_destroy]
+  #   defaults:
+  #     run:
+  #       working-directory: ./shared/boutique
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Setup Terraform Backend
-        id: backend
-        run: |
-          cat > backend.tf << EOF
-          terraform {
-            cloud {
-              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
-              workspaces {
-                name = "${{ secrets.TF_CLOUD_WORKSPACE_BOUTIQUE }}"
-              }
-            }
-          }
-          EOF
-      - name: Terraform Init
-        id: init
-        run: terraform init
+  #     - name: Setup Terraform Backend
+  #       id: backend
+  #       run: |
+  #         cat > backend.tf << EOF
+  #         terraform {
+  #           cloud {
+  #             organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
+  #             workspaces {
+  #               name = "${{ secrets.TF_CLOUD_WORKSPACE_BOUTIQUE }}"
+  #             }
+  #           }
+  #         }
+  #         EOF
+  #     - name: Terraform Init
+  #       id: init
+  #       run: terraform init
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
+  #     - name: Terraform Plan
+  #       id: plan
+  #       if: github.event_name == 'pull_request'
+  #       run: terraform plan -no-color -input=false
+  #       continue-on-error: true
 
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - uses: actions/github-script@v6
+  #       if: github.event_name == 'pull_request'
+  #       env:
+  #         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         script: |
+  #           const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+  #           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+  #           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+  #           <details><summary>Show Plan</summary>
+  #           \`\`\`\n
+  #           ${process.env.PLAN}
+  #           \`\`\`
+  #           </details>
+  #           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+  #           github.rest.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: output
+  #           })
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/destroy-waf-aws-ce' && github.event_name == 'push'
-        run: terraform destroy -auto-approve -input=false
+  #     - name: Terraform Apply
+  #       if: github.ref == 'refs/heads/destroy-waf-aws-ce' && github.event_name == 'push'
+  #       run: terraform destroy -auto-approve -input=false
 
-  terraform_eks_destroy:
-    name: "AWS EKS"
-    runs-on: ubuntu-latest
-    needs: [volt_mesh_site_destroy, terraform_boutique]
-    defaults:
-      run:
-        working-directory: ./aws/eks-cluster
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # terraform_eks_destroy:
+  #   name: "AWS EKS"
+  #   runs-on: ubuntu-latest
+  #   needs: [volt_mesh_site_destroy, terraform_boutique]
+  #   defaults:
+  #     run:
+  #       working-directory: ./aws/eks-cluster
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Setup Terraform Backend
-        id: backend
-        run: |
-          cat > backend.tf << EOF
-          terraform {
-            cloud {
-              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
-              workspaces {
-                name = "${{ secrets.TF_CLOUD_WORKSPACE_EKS }}"
-              }
-            }
-          }
-          EOF
+  #     - name: Setup Terraform Backend
+  #       id: backend
+  #       run: |
+  #         cat > backend.tf << EOF
+  #         terraform {
+  #           cloud {
+  #             organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
+  #             workspaces {
+  #               name = "${{ secrets.TF_CLOUD_WORKSPACE_EKS }}"
+  #             }
+  #           }
+  #         }
+  #         EOF
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+  #     - name: Terraform Init
+  #       id: init
+  #       run: terraform init
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
+  #     - name: Terraform Plan
+  #       id: plan
+  #       if: github.event_name == 'pull_request'
+  #       run: terraform plan -no-color -input=false
+  #       continue-on-error: true
 
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - uses: actions/github-script@v6
+  #       if: github.event_name == 'pull_request'
+  #       env:
+  #         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         script: |
+  #           const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+  #           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+  #           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+  #           <details><summary>Show Plan</summary>
+  #           \`\`\`\n
+  #           ${process.env.PLAN}
+  #           \`\`\`
+  #           </details>
+  #           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+  #           github.rest.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: output
+  #           })
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Terraform Destroy
-        if: github.ref == 'refs/heads/destroy-waf-aws-ce' && github.event_name == 'push'
-        run: terraform destroy -auto-approve -input=false
+  #     - name: Terraform Destroy
+  #       if: github.ref == 'refs/heads/destroy-waf-aws-ce' && github.event_name == 'push'
+  #       run: terraform destroy -auto-approve -input=false
 
     
   destorying_infra:
-    needs: [volt_mesh_site_destroy, terraform_boutique, terraform_eks_destroy]
+    #needs: [volt_mesh_site_destroy, terraform_boutique, terraform_eks_destroy]
     name: "AWS Infra"
     runs-on: ubuntu-latest
     defaults:
